export {Home} from "./Home"
export {Boxes} from "./Boxes"
export {Clothes} from "./Clothes"
export {Hats} from "./Hats"
export {Sinks} from "./Sinks"
export {Space} from "./Space"
export {Sunglasses} from "./Sunglasses"
export {Ties} from "./Ties"